apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: trialport
  labels:
    name: trial
    release: prometheus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
      - env:
        - name: JAEGER_HOST
          value: hotrod-traces-agent.observability.svc.cluster.local
        name: trial
        image: tkonthemove/observability_trial:latest
        imagePullPolicy: Always
        ports:
        - name: trialport
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: trial-service
  labels:
    app: trial # service-monitor target
spec:
  selector:
    app: trial # pod selection criteria
  ports:
    - name: trial # must exist for prometheus scraping
      port: 8082
      protocol: TCP
      targetPort: trialport
  type: LoadBalancer